title: Elham Ali, MPH, PMP
logo: https://raw.githubusercontent.com/Elhamyali/elhamyali.github.io/main/images/photo.jpg
description: >
  <br>
  Hi, Iâ€™m Elham ğŸ‘‹ğŸ½, a UX researcher and data science nerd with a decade of experience in design research, data analysis, program evaluation, and human-centered design in public health and civic tech.  
  <br><br>
  ğŸ“ As a doctoral student (DrPH) at Johns Hopkins University, I focus on using data science to advance equitable and sustainable food systems and climate resilience. I'm a scholar with the Crown Prince International Scholarship Program in Bahrain. 
  <br><br>
  <a href="https://www.linkedin.com/in/elhamali/">View my LinkedIn Profile</a> 

theme: jekyll-theme-minimal

colors:
  crimson: '#900C3F'
